version: '3.3'
services:
  web: &web
    image: 108sharing_server_demo
    environment:
      REDIS_URL: redis://redis:6379
      DISABLE_BASIC_AUTH: disable
      RAILS_MASTER_KEY: abcd1234
      DATABASE_URL: postgres://postgres:@db/108sharing_server_production
      USE_LOCAL_STORAGE: "yes"
      # USE_SECURE_SESSION: 1
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    ports:
      - ${PORT:-3000}:80
    depends_on:
      - db
      - redis
    volumes:
      - storage:/app/storage

  worker:
    <<: *web
    restart: always
    command: sidekiq
    ports: []
    depends_on:
      - db
      - redis
    volumes:
      - storage:/app/storage

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: 108sharing_server_production
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis:/data

volumes:
  db:
  redis:
  storage:
